### ISSUE TITLE
Never gets updated

### ISSUE THREAD

**Issue by okarpov** [aberus/ImageVisualizer#11]
in VS 2019 it always says 0.7.0 version and always propouses to download 0.8.0 version
you download it, install and all again - 0.7.0 and available 0.8.0 update endless

**Comment by aberus** [comment]
Thx for reporting. I found the culprit.
https://github.com/aberus/ImageVisualizer/blob/2afdf675a55d3eb444364a8c86f06171b8b59aef/src/ImageVisualizerPackage/source.extension.vsixmanifest#L4

Will be fixed in the next version.

**Comment by aberus** [comment]
Fixed with a27c6d79f4337f9558e6a42b4dc0e10bee9c7a83
