### ISSUE TITLE
VS Preview 2022 Error

### ISSUE THREAD

**Issue by Solips1sm** [aberus/ImageVisualizer#19]
![image](https://github.com/aberus/ImageVisualizer/assets/100047272/3d22ae14-e33c-406d-b0d0-3b13a96aa834)

Just installed via the .msi 1.1.0 version - getting this error on init. 

(Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.5.0 Preview 2.0)

**Comment by mitchcapper** [comment]
Thew new one is designed for 17.6 and higher, it will have to be a compile time conditional for calling the base class for supporting earlier vs versions.

**Comment by aberus** [comment]
New version released with a fix. First you need to uninstall the current version.
