### ISSUE TITLE
Support for Xamarin.Forms.Image

### ISSUE THREAD

**Issue by MagicAndre1981** [aberus/ImageVisualizer#2]
Can you please add [Xamarin.Forms.Image](https://developer.xamarin.com/api/type/Xamarin.Forms.Image/) support?

**Comment by aberus** [comment]
There is no plan to support other image types, maybe after version 1.0 (at end of the year).
Non .NET built-in image types require additional libraries, frameworks and/or runtimes and this can cause some problems.
