### ISSUE TITLE
Publish VSIX installer on marketplace

### ISSUE THREAD

**Issue by paolofulgoni** [aberus/ImageVisualizer#3]
Please provide a VSIX installer on the Visual Studio marketplace.
At the moment only the .msi of version 0.3 is available, but I see from the changelog that you already created the VSIX one for version 0.4

**Comment by aberus** [comment]
Version 0.4 is released. Installation hasn't changed. Visualizer is still installed trough MSI.

VSIX installer doesn't support installation of Visual Studio debug visualizers. I had to revert back to MSI from VSIX installer, sadly :(

The upside is that MSI installer installs now VS Package. This enables that updates can be handled trough Visual Studio's Tools -> Extensions and Updates menu.

**Comment by paolofulgoni** [comment]
OK, thanks for the clarification!
