### ISSUE TITLE
Add support for VS 2022

### ISSUE THREAD

**Issue by klausdost** [aberus/ImageVisualizer#9]
The debug visualizer does currently not work with VS 2022, because the ImageForm.UIFont property references the wrong version for dteProgID.

**Comment by aberus** [comment]
Support for VS 2022 will be available in next version 0.9 🚀. Currently waiting that Wix installer gets updated for VS 2022 https://github.com/wixtoolset/wix3/pull/542.

**Comment by CyberBotX** [comment]
I decided to clone the repo locally to build the extension before it gets released, using the master branch, but as far as I can tell, the targets still point to Visual Studio 2019 and earlier, and there does not appear to be a separate project for targeting Visual Studio 2022. Does this mean that the project has not actually been updated to work with VS 2022 yet despite the Wix installer issue mentioned above? Also it appears that said issue was closed 4 days ago.

**Comment by aberus** [comment]
Meanwhile, you can use [feature/vs2022](https://github.com/aberus/ImageVisualizer/tree/feature/vs2022) branch. You only need to build ImageVisualizer17.UI (ImageVisualizer17.DebuggeeSide and ImageVisualizer17.Common) project(s) and unload other non ImageVisualizer17.* projects if causing you trouble.

Copy 
ImageVisualizer17.UI\bin\Release\Aberus.VisualStudio.Debugger.ImageVisualizer.Common.dll
ImageVisualizer17.UI\bin\Release\Aberus.VisualStudio.Debugger.ImageVisualizer.UI.dll
to
C:\Program Files\Microsoft Visual Studio\2022\<Edition>\Common7\Packages\Debugger\Visualizers

Copy
ImageVisualizer17.DebuggeeSide\bin\Release\net40\Aberus.VisualStudio.Debugger.ImageVisualizer.Common.dll
ImageVisualizer17.DebuggeeSide\bin\Release\net40\Aberus.VisualStudio.Debugger.ImageVisualizer.DebuggeeSide.dll
to
C:\Program Files\Microsoft Visual Studio\2022\<Edition>\Common7\Packages\Debugger\Visualizers\net2.0

Copy
ImageVisualizer17.DebuggeeSide\bin\Release\netcoreapp3.0\Aberus.VisualStudio.Debugger.ImageVisualizer.Common.dll
ImageVisualizer17.DebuggeeSide\bin\Release\netcoreapp3.0\Aberus.VisualStudio.Debugger.ImageVisualizer.DebuggeeSide.dll
to
C:\Program Files\Microsoft Visual Studio\2022\<Edition>\Common7\Packages\Debugger\Visualizers\netcoreapp

And you are all set to go.

**Comment by aberus** [comment]
Long awaited update for the Debugger Image Visualizer extension is now available for Visual Studio 2022.
